### ISSUE TITLE
Invalid Access token if used entry

### ISSUE THREAD

**Issue by aneeskhan47** [MacsiDigital/laravel-zoom#100]
Hi,

i'm using this package v4.1 & laravel 8.. if i use the custom entry constructor it gives me invalid access token error but if i use the default zoom.php config (have the ZOOM_CLIENT_KEY and ZOOM_CLIENT_SECRET stored in env) it works :/

what could be the problem?

here is the code:

```php
new \MacsiDigital\Zoom\Support\Entry(auth()->user()->zoom_api_key, auth()->user()->zoom_api_secret);

$zoomUser = Zoom::user()->find('me')->get();

dd($zoomUser); // gives invalid access token error
```

**Comment by philharmonie** [comment]
What was your solution? Where did you get the correct key from?
