### ISSUE TITLE
Getting "zoom class does not exist" error when running tests

### ISSUE THREAD

**Issue by SuperDJ** [MacsiDigital/laravel-zoom#104]
-|-
-|-
PHP|8.0
PHPUnit|9.5
Laravel|8.55
LaravelZoom|4.1.9

When running PHPUnit tests I get the following error:
>ReflectionException: Class "zoom" does not exist in vendor/laravel/framework/src/Illuminate/Container/Container.php:873
Stack trace:

When using
```php
use MacsiDigital\Zoom\Facades\Zoom;

Zoom::user()->get();
```

In the `MacsiDigital\Zoom\Facades\Zoom` class. it tries to get a `zoom` class that does not exist.
```php
protected static function getFacadeAccessor()
{
     return 'zoom';
}
```

**Comment by colinhall17** [comment]
Hi @SuperDJ 

Are you requiring the ServiceProvider in your test setup?

**Comment by SuperDJ** [comment]
@colinhall17 I use auto discovery. 

After looking into a bit more I found that adding the `MacsiDigital\Zoom\Providers\ZoomServiceProvider::class,` class to the providers array in `config/app` did solve the error. Perhaps this should be mentioned in the docs.
