### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by MaizerGomes** [MacsiDigital/laravel-zoom#114]
Can laravel 9 support be added?

**Comment by jdrieghe** [comment]
I created a PR for this last week https://github.com/MacsiDigital/laravel-zoom/pull/111

**Comment by colinhall17** [comment]
Now updated

**Comment by jdrieghe** [comment]
Thanks, @colinhall17.
After trying to install it, I noticed the macsidigital/laravel-api-client package relies on MacsiDigital/laravel-oauth2-client which does not allow installation under Laravel 9 yet. I created a PR for it here: https://github.com/MacsiDigital/laravel-oauth2-client/pull/5
