### ISSUE TITLE
toArray method not working on any model

### ISSUE THREAD

**Issue by ArhamArham** [MacsiDigital/laravel-zoom#116]
Too few arguments to function MacsiDigital\API\Support\Resource::__construct(), 0 passed in C:\laragon\www\*******\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php on line 2099 and at least 1 expected

**Comment by simonbuehler** [comment]
@ArhamArham same here, did you find a way to fix it?

**Comment by simonbuehler** [comment]
@colinhall17 could you have a look int this, i kinda breaks the whole package :/

**Comment by leandrovitto** [comment]
Not Work, please help

**Comment by colinhall17** [comment]
This was fixe don the underlying API library, make sure its pulling version 4.0.2 of the API library

**Comment by colinhall17** [comment]
This was fixe don the underlying API library, make sure its pulling version 4.0.2 of the API library
