### ISSUE TITLE
Returning 401 error while keys are correct

### ISSUE THREAD

**Issue by hamidrostami** [MacsiDigital/laravel-zoom#12]
I used this script with my platform but receiving 401 error which is related to authorization. I also used this article to check the API with Postman :

https://marketplace.zoom.us/docs/guides/tools-resources/postman/using-postman-to-test-zoom-apis

and works fine with JWT token code .

How can I make it work with laravel-zoom, where there is no option to add JWT token code!?

**Comment by hamidrostami** [comment]
Ok I found the problem, laravel coudnot get the config keys inside config/zoom.php, So i just moved the keys into the config/services.php and everything is now ok.

**Comment by colinhall17** [comment]
What version of Laravel are you using?  

I just tried in Laravel 6.* and it found the zoom config both with and without publishing the config file.

**Comment by hamidrostami** [comment]
Laravel 5.8

**Comment by xaniuskarlhall** [comment]
I am facing the same issue with the status code 401. I did the same thing that @hamidrostami did by using postman and it worked, but with this package is does not work.  I am currently using Laravel version 7.0. What can I do to get this working?

**Comment by hdytarsn** [comment]
> I am facing the same issue with the status code 401. I did the same thing that @hamidrostami did by using postman and it worked, but with this package is does not work. I am currently using Laravel version 7.0. What can I do to get this working?

laravel 7-> Same issue for me

**Comment by bohraji** [comment]
@colinhall17  I had the same issue, but intermittently. 

I suspect, the fixed 60 seconds JWT token expiry duration could be the cause, as in our application we queue the requests to create meetings, which gets processed based on the system traffic.

It almost always works on local, but intermittently keeps failing on the testing environment. I tried increasing the temporarily increasing the JWT token expiry duration and it has been working since. 

Any thoughts/ suggestions on this would be great.

**Comment by colinhall17** [comment]
Hi all

Apologies in the delay in coming back to you, when I created this package it was a quick build for a project I needed it for and I made it open source in case it would help someone. 

With the increased use of Zoom around the world its gaining some traction, so I've built 3 new versions for Laravel 5.5 upwards, make sure you select the correct version for your version of Laravel.

The new version uses a week long duration on the JWT token, you can also change this in the config file.

Open a new issue with any problems.
