### ISSUE TITLE
ArgumentCountError: Too few arguments to function MacsiDigital\API\Support\Resource::__construct()

### ISSUE THREAD

**Issue by Mohamed-Abdalhamed99** [MacsiDigital/laravel-zoom#121]
i am trying to get list of users from zoom account

this my code 

public function getUsers(){
        $users = Zoom::user()->get();
        return response()->json($users);
    }

it return ArgumentCountError: Too few arguments to function MacsiDigital\API\Support\Resource::__construct(), 0 passed in C:\xampp\htdocs\a\academeyat_back\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php on line 2107 and at least 1 expected in file C:\xampp\htdocs\a\academeyat_back\vendor\macsidigital\laravel-api-client\src\Support\Resource.php on line 15

**Comment by MatthewLoffredo** [comment]
I'm having the same issue, I'm unable to log the ResultSet using ->toArray() or ->toJson(). It's giving me the same error as above.

**Comment by colinhall17** [comment]
This was fixe don the underlying API library, make sure its pulling version 4.0.2 of the API library
