### ISSUE TITLE
Too few arguments to function MacsiDigital\API\Support\Resource::__construct(), 0 passed in E:\Altayeb (Don't tuch)\learning-doctors\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php on line 2098 and at least 1 expected

### ISSUE THREAD

**Issue by AltayebRabeh** [MacsiDigital/laravel-zoom#122]
Too few arguments to function MacsiDigital\API\Support\Resource::__construct(), 0 passed in E:\Altayeb (Don't tuch)\learning-doctors\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php on line 2098 and at least 1 expected

**Comment by hellohasan** [comment]
@AltayebRabeh I also face this issue, are you fixed it anyhow?

**Comment by colinhall17** [comment]
This was fixe don the underlying API library, make sure its pulling version 4.0.2 of the API library
