### ISSUE TITLE
listing meetings related to a specific registrant

### ISSUE THREAD

**Issue by hamidrostami** [MacsiDigital/laravel-zoom#13]
I am trying to list all meetings joined by a specific registrant using this script .

 
code:
```

$zoom = new \MacsiDigital\Zoom\Zoom;
$meetings = $zoom->user->find('example@yahoo.com')->meetings()->all();

 $meetings_users = $zoom->user->all();


$meeting_of_user = array();
foreach($meetings as $meeting){

     die(var_dump($meeting->registrants()->get([
         'status' => 'approved',
         'page_size' => '30',
         'page_number' => '1'
     ])));

}
```
I can list all meetings found by that user but I need to list meetings joined by specefic registerant so I can show the meetings in the user profile.

This code returns 404 status code.

**Comment by hamidrostami** [comment]
I hoped this method works but wrong one. 

`        $meetings = $zoom->registrant->find('example@yahoo.com')->meetings()->all();
`

**Comment by colinhall17** [comment]
Registrants are not a full model in zoom, they have to be a relationship of a meeting or a webinar.  I will update the code

**Comment by colinhall17** [comment]
Hi

Apologies in the delay in coming back to you, when I created this package it was a quick build for a project I needed it for and I made it open source in case it would help someone. 

With the increased use of Zoom around the world its gaining some traction, so I've built 3 new versions for Laravel 5.5 upwards, make sure you select the correct version for your version of Laravel.

In the new version you should be able to get registrants easier by foreach looping over the meetings and pulling in the registrants.

The documentation is now also a lot more detailed

Open a new issue with any problems.
