### ISSUE TITLE
This package does not support Laravel < 5.8.*

### ISSUE THREAD

**Issue by faisalfayazkhan** [MacsiDigital/laravel-zoom#21]
While installing this package via composer , the package gives incompatibility error. Precise error message is given below.
 - don't install illuminate/support v7.3.0|don't install laravel/framework v5.7.21
 - Installation request for laravel/framework (locked at v5.7.21, required as 5.7.*) 

Thanks,
Faisal Khan

**Comment by colinhall17** [comment]
Hi all

Apologies in the delay in coming back to you, when I created this package it was a quick build for a project I needed it for and I made it open source in case it would help someone. 

With the increased use of Zoom around the world its gaining some traction, so I've built 3 new versions for Laravel 5.5 upwards, make sure you select the correct version for your version of Laravel.

Open a new issue with any problems.
