### ISSUE TITLE
Status code 201

### ISSUE THREAD

**Issue by ivanmv1987** [MacsiDigital/laravel-zoom#23]
When I create a new user the api status code response is 201 instead 200.
In the model User line 91

**Comment by colinhall17** [comment]
Hi

Apologies in the delay in coming back to you, when I created this package it was a quick build for a project I needed it for and I made it open source in case it would help someone. 

With the increased use of Zoom around the world its gaining some traction, so I've built 3 new versions for Laravel 5.5 upwards, make sure you select the correct version for your version of Laravel.

We now just check for a successful status code.

Open a new issue with any problems.
