### ISSUE TITLE
error when list all meeting

### ISSUE THREAD

**Issue by shankar-bavan** [MacsiDigital/laravel-zoom#24]
Got this error when I list all meeting

```
Argument 1 passed to MacsiDigital\Zoom\Support\Response::__construct() must be an instance of GuzzleHttp\Psr7\Response, null given, called in 'zoomtest\vendor\macsidigital\laravel-zoom\src\Interfaces\Base.php on line 15
```

```
$zoom = new \MacsiDigital\Zoom\Zoom;
$meetings = $zoom->user->find('manojmchathurangam@gmail.com')->meetings()->all();
```

**Comment by colinhall17** [comment]
Hi

Apologies in the delay in coming back to you, when I created this package it was a quick build for a project I needed it for and I made it open source in case it would help someone. 

With the increased use of Zoom around the world its gaining some traction, so I've built 3 new versions for Laravel 5.5 upwards, make sure you select the correct version for your version of Laravel.

Open a new issue if this is still an issue.
