### ISSUE TITLE
User all() giving collection of last object

### ISSUE THREAD

**Issue by alokpaidalwar** [MacsiDigital/laravel-zoom#3]
When fetching all the users using all(). Collection from collect() giving last user only.
```
       $zoom = new \MacsiDigital\Zoom\Zoom;
	$users = $zoom->user->all();
```
For eg. If two users are present User A and User B. Than collection method is returing collection of two items but having same user i.e Last User B.

However using some trick, I am getting a correct result now.
Model.php
```
public function make($attributes)
    {
        $new_class = new $this;

        foreach ($attributes as $attribute => $value) {
            $new_class->$attribute = $value;
        }

        return $new_class;
    }

```
Is it correct ?

**Comment by colinhall17** [comment]
I found the issue, in the make method it was still updating the initial model, rather than instantiating a new model.  I have now released a fix.
