### ISSUE TITLE
Meeting Registrants

### ISSUE THREAD

**Issue by craiglockhart81** [MacsiDigital/laravel-zoom#31]
The Create Meeting Registrant does not return the registrant_id

https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetingregistrantcreate

**Comment by colinhall17** [comment]
Hi

Apologies in the delay in coming back to you, when I created this package it was a quick build for a project I needed it for and I made it open source in case it would help someone. 

With the increased use of Zoom around the world its gaining some traction, so I've built 3 new versions for Laravel 5.5 upwards, make sure you select the correct version for your version of Laravel.

In the new version we will receive a registrant object back from a create or update call.

Open a new issue with any problems.
