### ISSUE TITLE
Disable waiting room

### ISSUE THREAD

**Issue by kezern** [MacsiDigital/laravel-zoom#33]
I have successfully created new meetings, but I can't disable waiting room.
This is my code.
```
$meeting = $user->meetings()->create([
                'topic' => $request["titulo"],
                'type' => '2',
                'password' => rand(100000,999999),
                'duration' => $request['duracion'],
                'start_time' => $fecha_inicio->toDateTimeLocalString(),
                'settings' => [
                    'host_video'=>false,
                    'join_before_host'=>true,
                    'waiting_room'=>false,
                    'approval_type'=>2,
                ]
            ]);
```
As you can see I have setted false to waiting_room parameter, but it is created as true.

**Comment by colinhall17** [comment]
Hi

Apologies in the delay in coming back to you, when I created this package it was a quick build for a project I needed it for and I made it open source in case it would help someone. 

With the increased use of Zoom around the world its gaining some traction, so I've built 3 new versions for Laravel 5.5 upwards, make sure you select the correct version for your version of Laravel.

Check the documentation on how to create settings.

Open a new issue with any problems.
