### ISSUE TITLE
Wrong Method 

### ISSUE THREAD

**Issue by abiralo** [MacsiDigital/laravel-zoom#34]
![image_2020_05_28T13_07_08_395Z](https://user-images.githubusercontent.com/6129033/83155146-c5efab80-a122-11ea-815b-6181685705c0.png)

**Comment by colinhall17** [comment]
Hi @abiralo

Its quite hard to know what you are trying to do, can you provide more detail.

It also looks like you  are using v1 which we no longer update, try one of the new versions.

V2 for Laravel 5.5 - 5.8,
V3 for Laravel 6
V4 for Laravel 7

**Comment by abiralo** [comment]
Hello, 
I used Laravel 5.7 and download the package and configure it.
V2 for Laravel 5.5 - 5.8

**Comment by colinhall17** [comment]
Ok .closing the ticket.
