### ISSUE TITLE
HTTP Request returned Status Code 401. Invalid access token

### ISSUE THREAD

**Issue by smockermaster** [MacsiDigital/laravel-zoom#35]
Hello friends,

I'm just trying to implement a simply meeting interfaz. When I try to get a meeting, I use

`dd( \Zoom::meeting()->find('12345678901') ); // 11 digit meeting ID`

And get this error

`MacsiDigital\API\Exceptions\HttpException
HTTP Request returned Status Code 401. Invalid access token.`

**Comment by smockermaster** [comment]
Sorry, I've really fixed it.

I was trying to use my profile Key and Secret. However, a quick read to JWT API Documentation, gave me the solution.

I must generate my own foreign application token from ZOOM App Marketplace.

Best regards!

**Comment by mahmoudhaggag641** [comment]
@smockermaster Please, i face same problem

How to generate my own foreign application token from ZOOM App Marketplace?

Thanks in advance
