### ISSUE TITLE
I have a problem when I publish my web in the hosting

### ISSUE THREAD

**Issue by bit503sv** [MacsiDigital/laravel-zoom#36]
Hello! I have been using this library to connect the zoom api with my laravel project, everything works fine in my local environment, but when I upload my project to production hosting, the library throws the following error:

**Declaration of MacsiDigital\API\Support\Entry::setRequest($request) must be compatible with MacsiDigital\API\Contracts\Entry::setRequest(MacsiDigital\API\Contracts\Client $request)**

I will appreciate your valuable help.

**Comment by colinhall17** [comment]
Ok there was an issue in the underlying API library which is now fixed.

Make sure that composer brings in the correct laravel-api-client version

v1.0.20 for v2 of laravel-zoom
v2.0.7 for v3 of laravel-zoom
v3.0.6 for v4 of laravel-zoom
