### ISSUE TITLE
FatalThrowableError (E_RECOVERABLE_ERROR)

### ISSUE THREAD

**Issue by bit503sv** [MacsiDigital/laravel-zoom#37]
I have the following error:
Argument 1 passed to MacsiDigital\API\Support\Relations\HasMany::save() must be an instance of MacsiDigital\API\Support\Relations\object, instance of MacsiDigital\Zoom\Meeting given.

When I try to save a new meeting from my hosting, in local environment that go with no problems.

**Comment by sid9841** [comment]
How was the problem solved?
