### ISSUE TITLE
StoreWebinar Request 

### ISSUE THREAD

**Issue by drilon-tahiri** [MacsiDigital/laravel-zoom#38]
There is a grammar error in StoreWebinar Request. 

"settings" => StoreWebianrSetting::class,

Fix => "settings" => StoreWebinarSetting::class

Thank you

**Comment by colinhall17** [comment]
Thanks, 

Now fixed across all versions.

**Comment by salmansafdar778** [comment]
Hello there,
Please tell me how can i correct this one ... i'm facing the same issue ... i search this "settings" => StoreWebianrSetting::class, in my whole project i didn't find any thing.

**Comment by colinhall17** [comment]
Update to the latest version
