### ISSUE TITLE
Issue with Webinars

### ISSUE THREAD

**Issue by colinhall17** [MacsiDigital/laravel-zoom#40]
V3 of the API Webinars

Registrant returning bad Method call

BadMethodCallException :- Call to undefined method MacsiDigital\Zoom\Support\Entry::registrant()

Then for the panelists, it created successfully, but when I checked the webinar on zoom dashboard, the created panelist was not reflecting there

**Comment by colinhall17** [comment]
Registrants cannot be accessed directly, you can only load registrants through either the webinar or meeting.  THe below code is an example

$webinar = Zoom::webinar()->find(....id.....);

$webinar->registrants()->create([
	'first_name' => 'Test',
    'email' => 'test@exapmle.com'
]);

Issue with panelists is fixed in latest release

**Comment by salahy** [comment]
Hello, I tried the same code but for meeting I get 
`Call to undefined method MacsiDigital\Zoom\Support\Entry::registrant()
`
