### ISSUE TITLE
"Class 'MacsiDigital\Zoom\Requests\StoreWebianrSetting' not found"

### ISSUE THREAD

**Issue by salmansafdar778** [MacsiDigital/laravel-zoom#43]
Hi,
I'm creating the webinar with settings when i save the webinar it throw above exception.
Please help me i'm using laravel-zoom 2.0 and here is my backend code with exception screenshot.
Thanks
Regards,
Salman Safdar
$settings = [
      'approval_type' =>  2,
      'panelists_video'=> true,
      'host_video'=>true,
      'audio'=>'both',
      'question_answer'=>true,
      'practice_session'=>true,
      'auto_recording'=>'none',
      'meeting_authentication'=>true,
    ];

    $webData = [
      'topic' => $data['topic'],
      'agenda' => $data['agenda'],
      'type' => 5,
      'start_time' => new Carbon('2020-08-12 10:00:00')
      'duration' => $duration,
      'timezone'=> $timezone,
      'password'=>$password,
      'settings'=>$settings,
        ];

    $webinar = \Zoom::webinar()->make($webData);
    $webinar->settings()->make($settings);
    $webinar->save();

![Screenshot_2020-06-24 Whoops There was an error ](https://user-images.githubusercontent.com/67374181/85558667-65c92800-b642-11ea-92c2-682c8712b078.png)

**Comment by salmansafdar778** [comment]
I fix it by myself ... by correcting the name of the this class in storeWebinar.Now i got this error when i create the webinar.
![image](https://user-images.githubusercontent.com/67374181/85657573-a751e580-b6cb-11ea-898f-dddd68aeef3e.png)

**Comment by salmansafdar778** [comment]
Thanks

**Comment by colinhall17** [comment]
Hi

If you update in composer it will bring in the latest version, which fixes the typo issue.

A 405 is a 'Method not allowed' exception.  This is likely because you are not saving it as part of a user but trying to save it directly.

If you refer to the documentation you will see how you have to save it.

$webinar = Zoom::webinar()->make([...]);
$user = Zoom::user()->find(id)->webinars()->save($webinar);

**Comment by salmansafdar778** [comment]
it works....:) thanks.
