### ISSUE TITLE
How can i update the webinar settings?

### ISSUE THREAD

**Issue by salmansafdar778** [MacsiDigital/laravel-zoom#44]
Please help me I can't figure it out how I can update the webinar settings.
Below is the functions i call for update .... it only update the webinar not webinar setting things like video Host/Panelists ON/OFF is not updated.

$webinar = \Zoom::webinar()->find($webinarId);
$webinar->fill($webinarData)->save();
$webinar->settings()->fill($settings);

**Comment by colinhall17** [comment]
Hey @salmansafdar778 

Are you saving the webinar after updating the settings?

**Comment by colinhall17** [comment]
There was a bug which is now fixed, but don't forget to call $webinar->save() after filling the settings.

You will need to update you dependencies in your project
