### ISSUE TITLE
Access token

### ISSUE THREAD

**Issue by wontone18** [MacsiDigital/laravel-zoom#45]
Hi

I am using this first time and having all my client key  and secret. But while getting these information zoom asking for auth Redirect URL for OAuth and Whitelist URL. I want to know which app type you are using for this Jwt?

This is the error i am getting "HTTP Request returned Status Code 401. Invalid access token. "

**Comment by colinhall17** [comment]
If its asking for OAuth URL's you are have created an OAuth App.  A JWT app doesn't use OAuth, just a JWT token that is passed in the authorisation header.

In Zoom you can only create 1 JWT app per dev account as its intended for server to server integrations on your own website.

We are currently adding OAuth support but its not ready yet.

**Comment by wontone18** [comment]
Hi

I am using JWT app, yes its only a one app. https://www.99mod.com/zoom/public/zoom here is the url.

I also have given a event subscription all permission. But still its same error access token.

**Comment by wontone18** [comment]
i am checking the  api key in postman it works fine. But in laravel it having a problem with the access token.

**Comment by colinhall17** [comment]
Hi

What version of the API are you using?

Are you setting  ZOOM_CLIENT_KEY and ZOOM_CLIENT_SECRET in your .env file?

**Comment by wontone18** [comment]
Are you setting ZOOM_CLIENT_KEY and ZOOM_CLIENT_SECRET in your .env file?

yes i already having these config in .env file

**Comment by colinhall17** [comment]
What version of the API are you using?

**Comment by wontone18** [comment]
> What version of the API are you using?

 "macsidigital/laravel-zoom": "^4.0" version am using.

**Comment by colinhall17** [comment]
Ok, then the issue is in your API credentials, as noted in the zoom documentation

401 | Unauthorized | Invalid/missing credentials

So you need to make sure your credentials are passing to the config file, try dd(config('zoom.api_key')) and see if it returns your api_key and do the same for secret to make sure both values are set.  Also check them against your app values in Zoom.

Finally, make sure your config is not being cached, clear your cache and retry to see if it is being populated.

**Comment by wontone18** [comment]
hmm all my settings are correct. This same key and secret  i already tested it in postman also. Its working from there. https://www.99mod.com/zoom/public/zoom its giving a null.

Zoom client and secret config i already set in .env and config/zoom.php

**Comment by colinhall17** [comment]
OK you could try doing a composer dump-autoload.

or in the command line try php artisan config:clear

You can also try publishing the zoom config file by running:-

php artisan vendor:publish --provider="MacsiDigital\Zoom\Providers\ZoomServiceProvider"

**Comment by wontone18** [comment]
:) php artisan vendor:publish --provider="MacsiDigital\Zoom\Providers\ZoomServiceProvider" this one we are already doing after your package installation. 

 php artisan config:clear i already done this. Its all same. i am having laravel 7 version by the way.

**Comment by wontone18** [comment]
so will this work? i tried it all with this script. its not working.

**Comment by colinhall17** [comment]
Can you try outputting env('ZOOM_CLIENT_KEY') to see what it returns.

**Comment by wontone18** [comment]
empty page https://www.99mod.com/zoom/public/zoom i will send you my project folder. it having my api code. if you prefer in your email.

**Comment by colinhall17** [comment]
Sorry, you would have to dd(env('ZOOM_CLIENT_KEY'))

**Comment by wontone18** [comment]
dd(env('ZOOM_CLIENT_KEY')) or echo(env('ZOOM_CLIENT_KEY')) correct one.

yes it is printing the code. check the url above.

**Comment by colinhall17** [comment]
Ok then I think it's definitely a caching issue,

Can you do dd(config('zoom'))

**Comment by wontone18** [comment]
colin i got the issue config/zoom.php we should remove the 'env'. because it is not reading the .env file. After removing that env from the config/zoom.php api is working fine.

https://www.99mod.com/zoom/public/zoom

**Comment by wontone18** [comment]
:( ops i got the issue. Actually i am having api keys and secret written in both config/zoom.php and also .env. so it was unable to get through the details. Now it is corrected and working fine.
