### ISSUE TITLE
Feature Request: Get User's Recording

### ISSUE THREAD

**Issue by albalooshi** [MacsiDigital/laravel-zoom#47]
Any plans on implementing this?
https://marketplace.zoom.us/docs/api-reference/zoom-api/cloud-recording/recordingslist

**Comment by albalooshi** [comment]
@colinhall17 is there any ETA for this enhancement?

**Comment by colinhall17** [comment]
Hi @albalooshi 

There is no time frame, it will be as and when we have the time to implement it as its an open source project.

**Comment by colinhall17** [comment]
Hi @albalooshi

We have now added the retrieval of recordings through

$user->recordings
$meeting->recording

You can only retrieve the recordings at present, there is no functionality to delete or amend the settings at present.
