### ISSUE TITLE
Working fine on localhost but displays error in server

### ISSUE THREAD

**Issue by sid9841** [MacsiDigital/laravel-zoom#49]
Argument 1 passed to MacsiDigital\API\Support\PersistResource::fill() must be an instance of MacsiDigital\API\Support\object, instance of MacsiDigital\Zoom\Meeting given,

**Comment by colinhall17** [comment]
Hi @sid9841,

Without seeing your code snippet its hard to help.

**Comment by sid9841** [comment]
I am using Laravel Version 5.7 and macsidigital/laravel-zoom version 2.0.* 
`  public function meetingStore(Request $request)
    {

        $this->validate($request, [
            'name'              =>  'required|max:191',
            'agenda'            =>  'required|string|max:2000',
            'start_time'        =>  'required|date',
            'duration'          =>  'numeric|max:30',
            'password'          =>  'nullable|string|min:3',
        ]);

        // dd(str_replace( 'T', '', $request->start_time ));
        $data =  [
            'topic' => $request->name,
            'agenda' => $request->agenda,
            'type' => 2,
            'start_time' =>  Carbon::createFromFormat('Y-m-d\TH:i', $request->start_time),
            'timezone' => 'Asia/Kathmandu',
            'duration' => $request->duration,
            'password' => $request->password,
            'settings' => [
                'join_before_host'  =>  false,
                'host_video'        =>  false,
                'participant_video' => false,
                'mute_upon_entry'   => false,
                'enforce_login'     => false,
                'auto_recording'    => "none",
                'alternative_hosts' => ""
            ]
        ];

        // dd($data);

        // Save Method
        // $meeting = Zoom::meeting()->make([...]);
        // Zoom::user()->find('id')->meetings()->save($meeting);
        // Create Method
        // $created = \Zoom::user()->find('id')->meetings()->create($data);

        $user = \Zoom::user()->find('me');


        if($user->meetings()->create($data)){
            $user = \Zoom::user()->find('me');
            $meetings = $user->meetings()->get();
            $meeting=$meetings->sortByDesc('created_at')->first();
            $new_meeting = new SmOnlineClass();
            $new_meeting->class_id= $request->class;
            $new_meeting->section_id=$request->section_id;
            $new_meeting->meeting_id=$meeting->id;
            $new_meeting->teacher_id=Auth::user()->id;
            $new_meeting->section_id=$request->section_id;
            $new_meeting->save();
            return redirect()->route("admin.meetings.index")
                ->withSuccess('Great! Meeting has been successfully added.');
        } else {
            return redirect()->back()
                ->withErrors('error','Meeting couldn\'t added.');
        }
    }`

**Comment by sid9841** [comment]
The error comes from 
    $user = \Zoom::user()->find('me');


    if($user->meetings()->create($data)){

**Comment by colinhall17** [comment]
Ok, I think I know what the issue is

We use an 'object' type hint which was only introduced in PHP 7.2, Laravel  5.5 - 5.8 only requires PHP7.0,  So I think your production environment is using < PHP7.2 whereas your local environment is 7.2 or greater.

I have corrected the issue in the library so if you are running < 7.2 then just do a composer update and it should pull in the latest release of the API Library (v1.0.26 of the macsidigital/laravel-api-client).

If you are running PHP 7.2 then reopen the ticket and we can look into further.

**Comment by sid9841** [comment]
I run the update but it updated from 2.0.6=>2.0.9.  1.0.* version of the package requires 7.2 but i am currently using php version 7.1.3.

**Comment by colinhall17** [comment]
The v1.0.28 refers to the macsidigital/laravel-api-client library and not the laravel-zoom library.  

You need to run at least v2 of the Laravel Zoom library, but when it pulls in the laravel-api-client as a dependency make sure it is the version listed.

**Comment by sid9841** [comment]
"require": {
                "illuminate/support": "^5.5",
                "macsidigital/laravel-api-client": "^1.0",
                "php": "^7.0|^7.1|^7.2|^7.3"
            },

**Comment by sid9841** [comment]
It is version 1.0. How can i update to 1.0.28?

**Comment by colinhall17** [comment]
You will only see the minor version when doing a composer update or by chekcing the composer lock file.  But if you updated it should be fine, check it in your production environment

**Comment by sid9841** [comment]
The same problem exists after doing composer update also.

**Comment by colinhall17** [comment]
Hi @sid9841 , 

just ran:-

use Carbon\Carbon;    

    $data =  [
        'topic' => 'Test Name',
        'agenda' => 'Test Agenda',
        'type' => 2,
        'start_time' =>  Carbon::now()->addDays(3),
        'timezone' => 'Asia/Kathmandu',
        'duration' => '60',
        'password' => 'Password',
        'settings' => [
            'join_before_host'  =>  false,
            'host_video'        =>  false,
            'participant_video' => false,
            'mute_upon_entry'   => false,
            'enforce_login'     => false,
            'auto_recording'    => "none",
            'alternative_hosts' => ""
        ]
    ];

    $user = \Zoom::user()->first();


    if($user->meetings()->create($data)){
     	return 'it works'; 
    } else {
        return 'it fails';
    }

and it returned "it works" without any errors.  So there is an issue in your environment that you need to work out.

This is using PHP Version 7.1.33-15+ubuntu18.04.1+deb.sury.org+1, and Zoom version 2.0.9

Unfortunately there is nothing we can do as its something specific to your environment.
