### ISSUE TITLE
Meeting Create Existing User

### ISSUE THREAD

**Issue by craiglockhart81** [MacsiDigital/laravel-zoom#5]
When trying to create a meeting on an existing user, it loses the user ID

Code to set meeting:
$zoom_meet = $zoom->meeting;
$zoom_meet->setUserID($meeting_host->zoom_id);
$zoom_meeting = $zoom_meet->create($meeting_obj);

--- ALSO TRIED
Attaching from the zoom user it found:
$zoom->user->find($zoom_search)->first()
$zoom_meeting = $zoom_meet->meetings()->create($meeting_obj);

-- This is the response before send

Meeting {#485 ▼
  #methods: array:5 [▶]
  #userID: null
  +response: null
  #attributes: array:16 [▼
    "uuid" => ""
    "id" => ""
    "host_id" => ""
    "created_at" => ""
    "join_url" => ""
    "topic" => "Test"
    "type" => 2
    "start_time" => "2019-07-28T13:00:00Z"
    "duration" => 60
    "timezone" => ""
    "password" => ""
    "agenda" => ""
    "recurrence" => []
    "occurrences" => []
    "tracking_fields" => []
    "settings" => []
  ]
  #createAttributes: array:11 [▶]
  #updateAttributes: array:11 [▶]
  #relationships: array:3 [▶]
  #query_string: ""
  #client: PrivateApplication {#157 ▶}

**Comment by colinhall17** [comment]
Hi

Issue fixed in version 1.0.10
