### ISSUE TITLE
Occurrence Save() after is not persisting

### ISSUE THREAD

**Issue by anasbakro** [MacsiDigital/laravel-zoom#50]
- API Version: 4.0.8
- Laravel Version: 7.19.0
- PHP Version: 7.2.5

**Describe the bug**
Occurrence Save() after ```    $occurrence->start_time = x ``` not persisting on Zoom

**To Reproduce**
1. Fetch Meeting
2. Fetch Occurrances
3.    $occurrence->start_time = $event->event_date->toIso8601ZuluString();
       $occurrence->save();

**Expected behavior**
Occurrence Date persist on Zoom

**Comment by colinhall17** [comment]
Hi @anasbakro

I have found the issue, Guzzle doesn't allow query parameters on any update methods.  I will work on a fix in the next couple of days.

**Comment by anasbakro** [comment]
Thank you very much

**Comment by colinhall17** [comment]
I've patched it, if you can try and let me know if there are any issues
