### ISSUE TITLE
Auto recording Cloud

### ISSUE THREAD

**Issue by piep14** [MacsiDigital/laravel-zoom#54]
Good evening, sir,

First of all I would like to congratulate you for your package which is great! 

I just have a little problem with the auto-recording cloud.

Here's what I did and yet when I launch the meeting, the recording doesn't start automatically.
Did I make a mistake? 

Thank you in advance 

```
$meeting = Zoom::meeting()->make([
    'topic' => 'REUNION',
    'type' => 2,
    'password' => 'PASSWORD',
    'start_time' => $request->start
]);

$meeting->settings()->make([
    'host_video' => true,
    'participant_video' => true,
    'join_before_host' => true,
    'mute_upon_entry' => true,
    'approval_type' => 2,
    'registration_type' => 1,
    'enforce_login' => false,
    'waiting_room' => false,
    'auto_recording' => 'cloud',
]);

$meeting = $user->meetings()->save($meeting);
```

**Comment by colinhall17** [comment]
Hi

Thanks for getting in touch, there was a typo in one of the validation files which was removing the auto_recording from the settings object.

We have now patched and released a new version. I will close the ticket but if there are any issues please do reopen.

**Comment by darshi12** [comment]
How to update this meeting auto_recording?
