### ISSUE TITLE
updatePassword not working

### ISSUE THREAD

**Issue by arubacao** [MacsiDigital/laravel-zoom#57]
- API Version: 4.0.10 (laravel-zoom version)
- Laravel Version: 7.26.1
- PHP Version: 7.3.18

**Describe the bug**
updatePassword is not working

**To Reproduce**
1. $user = Zoom::user()->find(...);
2. $user->updatePassword($password); 
3. See error `count(): Parameter must be an array or an object that implements Countable`

**Expected behavior**
Working updatePassword method

**Additional context**
Method flow in generell could not work

**Comment by colinhall17** [comment]
@arubacao 

Thanks for the PR, now implemented across all versions.
