### ISSUE TITLE
Recurring Weekly Meetings, weekly_days are supposed to be string, not integer.

### ISSUE THREAD

**Issue by icaroscherma** [MacsiDigital/laravel-zoom#60]
Following [Zoom Meetings documentation](https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetingcreate), if you're scheduling a meeting with recurrence type 2 (weekly), the parameter `weekly_days` should be string to support multiple days as comma separated value (i.e. `2,3,5,7`), but if we set it so we get an error saying that it must be integer.

For instance, below:
```PHP
<?php
$z = Zoom::user()->find('myemail@mydomain.com');
$zoomMeeting = $z->meetings()->make([
    'topic' => 'Recurring meeting weekly on tuesday,thursday and saturday',
    'type' => 8, // Recurring with specific time
    'start_time' => '2020-09-04T15:45:00',
    'duration' => 15,
    'timezone' => 'America/Vancouver',
]);
$zoomMeeting->recurrence()->make([
    'type' => 2, // Weekly
    'repeat_interval' => 1, // Every 1 week
    'weekly_days' => '3,5,7', // Tuesday, Thursday, Saturday
    'end_date_time' => '2020-09-11T16:00:00',
]);
$zoomMeeting->save();
```

The bug is not version specific but I'm using the latest Laravel 7.x with PHP 7.4.

**Comment by colinhall17** [comment]
Hi @icaroscherma , 

Thanks for pointing out the bug, now changed so weekly_days is an integer.
