### ISSUE TITLE
Unable to install on Laravel 8.x

### ISSUE THREAD

**Issue by Sami123sam** [MacsiDigital/laravel-zoom#62]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for macsidigital/laravel-zoom ^4.1 -> satisfiable by macsidigital/laravel-zoom[4.1.0].
    - Conclusion: remove laravel/framework v8.0.0
    - Conclusion: don't install laravel/framework v8.0.0
    - macsidigital/laravel-zoom 4.1.0 requires illuminate/support ^7.0|^8,0 -> satisfiable by illuminate/support[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.26.1, v7.27.0, v7.28.0, v7.28.1, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - don't install illuminate/support 7.x-dev|don't install laravel/framework v8.0.0
    - don't install illuminate/support v7.0.0|don't install laravel/framework v8.0.0
    - don't install illuminate/support v7.0.1|don't install laravel/framework v8.0.0
    - don't install illuminate/support v7.0.2|don't install laravel/framework v8.0.0

**Comment by colinhall17** [comment]
Hi @Sami123sam 

Apologies, typo in the composer file.  Now fixed and working

Thanks

**Comment by Sami123sam** [comment]
Thanks for helping.. it worked ! :)
