### ISSUE TITLE
Past Meetings

### ISSUE THREAD

**Issue by Sami123sam** [MacsiDigital/laravel-zoom#63]
Hi, when will be past meetings going to come in package

Thanks,

**Comment by colinhall17** [comment]
Hi @Sami123sam

From memory I think the models and function are there but I didn't document or test them.  If you check this file you can see the available methods.

https://github.com/MacsiDigital/laravel-zoom/blob/master/src/PastMeeting.php

But can't guarantee they are complete and working so will be a case of just trying them.

If they are not complete I don't have any time scale on when it will be added at present.

**Comment by Sami123sam** [comment]
Thanks for your support i appreciate it.
