### ISSUE TITLE
Need a method to get all participants in a meeting

### ISSUE THREAD

**Issue by hapu1993** [MacsiDigital/laravel-zoom#65]
Need a method to get all participants in a meeting

**Comment by colinhall17** [comment]
Hi @hapu1993 

Thanks for getting in touch.

You can get all registrants for a meeting with $meeting->registrants();

If you mean actual participants in the meeting as it is live then it's not possible through this Zoom API, you need to use Zoom webhooks which is not part of this package.

**Comment by simonbuehler** [comment]
as in the docs
https://marketplace.zoom.us/docs/api-reference/zoom-api/methods/#operation/meetingRegistrants

`status` string Default: "approved" filter only approved ones

how can i set the status to e.g.pending?
