### ISSUE TITLE
Storing the Meeting Response

### ISSUE THREAD

**Issue by seivad** [MacsiDigital/laravel-zoom#66]
Hey I can't seem to figure out how to store the response from a meeting being created. 

Starting with:

```
$meeting = $user->meetings()->create([...]);
```

I store the main items I need like the join_url and start_url but I cannot get the whole response back and keep a copy of it. I have tried different castings as well on the Text column which none worked.

I essentially get this back in the text column:

```
{"client":{},"exists":true,"wasRecentlyCreated":true,"passOnKeys":[]}
```

but when I use:

```
logger($meeting);
```

I get a really nice print out of everything that came back over the wire and/or same as when viewing the response in the browser using a JSON plugin.

What's the best way to get this into the DB column? Thanks in advance

**Comment by colinhall17** [comment]
Hi @seivad

What we return is what we get sent back from the API, which is not necessarily the whole object.  If you need the whole object from then its probably better you do a second query and find the object by its ID, which should then return a full object - we don't do this for performance reasons by default as it would mean a second API call for every saved model.

With regards to the fields that are returned, we hook into Laravels Model blueprint, so all of the actual fields are in an 'attributes' attribute which you can get back using any of the normal Laravel model functions.  so toArray() would return an array of all the attributes, I think there is toJson also.
