### ISSUE TITLE
Update Webinar Settings

### ISSUE THREAD

**Issue by mirkin** [MacsiDigital/laravel-zoom#69]
- API Version: 4.0
- Laravel Version: 8.0
- PHP Version: 7

I've tried many variations to update the settings for a webcast but always get
an error or the settings not updating.

MacsiDigital\Zoom\Webinar already has a set relationship from MacsiDigital\Zoom\WebinarSetting this is a One relationship and cna only have 1 set relation.

``
$webinar->find($id);
$webinar->settings()->make([
      'approval_type' => 1,
      'registration_type' => 2,
      'enforce_login' => false,
    ]);
$webinar->save();
``

**Comment by colinhall17** [comment]
Hi @mirkin 

Apologies been flat out with a project so only just noticed the issue, will try to have a look towards the week end.

**Comment by colinhall17** [comment]
Hi @mirkin 

Like Laravel, the make command will make a new object, once you have retrieved the webinar you should be able to interact directly with the setting object.

$webinar->settings->approval_type = 1; etc

Then if you save the webinar it should carry the settings with it.

Reopen if you have any issues.

Thanks
