### ISSUE TITLE
Webinar Settings doens't update

### ISSUE THREAD

**Issue by bm2ilabs** [MacsiDigital/laravel-zoom#75]
- API Version: 4.1.2
- Laravel Version: 8.20.1
- PHP Version: 7.4

When i try to update the webinar settings it doesn't apply

1 - get any webinar with Zoom::user()->find(id)->webinars()->first();
2 - Use $webinar->settings = [
registrants_confirmation_email => false
] or $webinar->settings->registrants_confirmation_email = false
3 - Save the webinar 

when i do $webinar->settings i should get registrants_confirmation_email is false but its always true

Thank you for this amazing package

**Comment by colinhall17** [comment]
Hi @bm2ilabs 

I no longer have a webinar subscription so its hard for me to test it to see what the issue is.  Are you receiving any errors in the returned output?
