### ISSUE TITLE
Download recording files, easily?

### ISSUE THREAD

**Issue by BioSehnsucht** [MacsiDigital/laravel-zoom#82]
I can borrow the JWT functionality (slightly modified copy paste from `src/Support/Entry.php`) to get a new token and append it to the URL with parameter `access_token` in order to download the files with curl, but this is a bit ugly. 

Is there a way to get the current active JWT token that laravel-zoom is itself using already, or better yet could we get added functionality for downloading files to make it a simple function call instead of doing all the curl ourselves? This is my first time using Laravel so there may be a really obvious solution that I just don't see (I don't even understand how the JWT calls work normally, since I didn't see where newRequest even gets called to get a JWT token to begin with ... )

Example code that works to show how I'm achieving this now (this is ugly test code just to figure out how to do it, after using some other ugly test code to find a download url for one of the recording files)
```php
    public function handle()
    {
        $zoom = new \MacsiDigital\Zoom\Support\Entry;
        $account = new \MacsiDigital\Zoom\User($zoom);
        $apiKey = config('zoom.api_key');
        $apiSecret = config('zoom.api_secret');
        $tokenLife = config('zoom.token_life');
        $jwtToken = JWT::generateToken(['iss' => $apiKey, 'exp' => time() + $tokenLife], $apiSecret);
        $outputFile = 'OUTPUT_FILENAME';
        $downloadUrl = 'YOUR_DOWNLOAD_URL_HERE';
        $fp = fopen($outputFile,'w+');
        $ch = curl_init($downloadUrl);
        curl_setopt($ch, CURLOPT_FILE, $fp);
        curl_setopt($ch, CURLOPT_POSTFIELDS, 'access_token=' . $jwtToken);
        // Need to follow 302 to the actual download
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        curl_exec($ch);
        $statusCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
        fclose($fp);
        $this->line('Curl: ' . $statusCode);
    }
```

**Comment by colinhall17** [comment]
Hi @BioSehnsucht 

The Zoom package utilises the Laravel HTTP client under the hood, which in turn uses the Guzzle HTTP Client.  As you are attaching the token to the URL you don't need to use the Zoom Entry Point, you can just use the Http Client direct.

So first you would need to build a JWT token

$jwtToken = \MacsiDigital\API\Support\Authentication\JWT::generateToken(['iss' => config('zoom.api_key'), 'exp' => time() + config('zoom.token_life')], config('zoom.api_secret'));

Then you can build the HTTP Client

$client = \MacsiDigital\Zoom\Support\Client::withToken($jwtToken);

Form there you can then use any of the Laravel HTTP methods which are listed in the link below

[https://laravel.com/docs/8.x/http-client#introduction](https://laravel.com/docs/8.x/http-client#introduction)

**Comment by BioSehnsucht** [comment]
it seems `::withToken(...)` doesn't exist? 

```
   BadMethodCallException

  Method MacsiDigital\Zoom\Support\Client::withToken does not exist.
```

Using the Http client directly with `withHeaders` works though.

**Comment by colinhall17** [comment]
Apologies it should have been

\Illuminate\Support\Facades\Http

and not 

\MacsiDigital\Zoom\Support\Client

You need to hook into Laravels HTTP Client

**Comment by BioSehnsucht** [comment]
You're right about the withToken thing for downloads, downloads pass it as a URL parameter. I did end up using withToken for getting recordings since I still haven't gotten the with/to functionality to work as it's supposed to (#67).
