### ISSUE TITLE
Error 400 when creating a new user

### ISSUE THREAD

**Issue by IServetnik** [MacsiDigital/laravel-zoom#83]
Hello

When I try to create a new user, I get a 400 error
Is it through what I do not have PRO zoom account?

```
$zoom = new Zoom();

$user = $zoom->user->create([
          'first_name' => 'First Name',
          'last_name' => 'Last Name',
          'email' => 'test@test.com',
          'password' => 'secret'
]); 
```

**Comment by mrabbani** [comment]
How did you solve this problem? @IServetnik

**Comment by IServetnik** [comment]
I had version 1.0 in my project and I updated to the latest and it resolved.
