### ISSUE TITLE
Retrieve meeting to add registrants issue 

### ISSUE THREAD

**Issue by salahy** [MacsiDigital/laravel-zoom#84]
Hello,
I am trying to retrieve meeting with id and add registrants to it but I get null when I try this

```
  $meeting = \MacsiDigital\Zoom\Contracts\Zoom::meeting();
  $meeting = $meeting->find($zoom_id); // THIS RETURN NULL
  $registrant = Zoom::registrant()->make([
      "email"=>$email,
      "first_name"=>$name,
      "auto_approve"=>true
  ]);
  $meeting->registrants()->save($registrant);
```

and even when I try this code alone I get

```
  $registrant = Zoom::registrant()->make([
      "email"=>$email,
      "first_name"=>$name,
      "auto_approve"=>true
  ]);
```

`Call to undefined method MacsiDigital\Zoom\Support\Entry::registrant()
`

**Comment by colinhall17** [comment]
HI @salahy 

Can you let me know which version you are working with

**Comment by salahy** [comment]
I was using column type integer to store the meeting, so it was truncated, all good now
