### ISSUE TITLE
Webinar Registrants Approval/Denial

### ISSUE THREAD

**Issue by Nievac** [MacsiDigital/laravel-zoom#86]
Is there a way using the package to approve or deny a registrant?

**Comment by colinhall17** [comment]
Hi @Nievac 

Thanks for reaching out, there are 3 functions on the meeting and webinar registrant models

    public function approve()
    {
        return $this->updateAction('approve');
    }

    public function deny()
    {
        return $this->updateAction('deny');
    }

    public function cancel()
    {
        return $this->updateAction('cancel');
    }

**Comment by Nievac** [comment]
Thanks.
