### ISSUE TITLE
How to open zoom ui 

### ISSUE THREAD

**Issue by souvik07manu** [MacsiDigital/laravel-zoom#88]
I can create meetings after creating the user.
After creating the meeting I am getting the meeting id and lots of info about this meeting.

I am creating an online education system.

The teacher will create a meeting here and the students will also join the meeting.

**But I don't understand how to open zoom ui on my website.**

please help me.

**Comment by colinhall17** [comment]
Hi @souvik07manu 

This API is only for the creation and admin of meetings and webinars.
