### ISSUE TITLE
Webinar settings do not persist

### ISSUE THREAD

**Issue by cyrillkalita** [MacsiDigital/laravel-zoom#90]
Two Webinar settings, when sent as 

```php
$webinar->settings()->make([
    'panelists_video' => true,
    'practice_session' => true,
]);
```

do not persist in Zoom. 

Issue is typo in `MacsiDigital\Zoom\Requests\StoreWebinarSetting`

**Comment by cyrillkalita** [comment]
@colinhall17 do you think you can maybe look at my PR?

**Comment by colinhall17** [comment]
@cyrillkalita now merged
