### ISSUE TITLE
Is there any api or sdk option for showing multiple screen on zoom window?

### ISSUE THREAD

**Issue by khurram753** [MacsiDigital/laravel-zoom#98]
What I wanted to do is when user can joins a meeting. User will see different screens and when user click on any of that meeting he joins that meeting and can switch between different meeting?

**Comment by colinhall17** [comment]
Hi, thanks for reaching out.

This library does not handle any of the actual meetings, just the creation and management of registrants.

You need to use the Zoom SDK to handle the actual meetings
